# Generated by Django 2.2 on 2021-06-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20210606_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
