# Generated by Django 2.2 on 2021-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20210606_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.TextField(),
        ),
    ]
