# Generated by Django 2.2 on 2021-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20210606_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
